# This workflow builds and pushes a Docker image to private  Container Registry


name: CI & Docker Build

on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

permissions:
  contents: read

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=registry.ceduth.dev/jfp/ytdt-api:latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG